"""Add Proposal model

Revision ID: adffd4ebdb02
Revises: 46775a9dcdb6
Create Date: 2024-12-30 12:30:46.369861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adffd4ebdb02'
down_revision: Union[str, None] = '46775a9dcdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sponsors_user_id'), 'sponsors', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsors_user_id'), table_name='sponsors')
    # ### end Alembic commands ###
