"""Update proposalstatus enum to lowercase

Revision ID: b3a38a86c563
Revises: adffd4ebdb02
Create Date: 2024-12-30 14:09:21.465197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a38a86c563'
down_revision: Union[str, None] = 'adffd4ebdb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
