"""Add user_id to sponsors

Revision ID: edeea8da7bd7
Revises: 49cf711175d5
Create Date: 2024-12-23 12:01:57.363174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edeea8da7bd7'
down_revision: Union[str, None] = '49cf711175d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sponsors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sponsors', type_='foreignkey')
    op.drop_column('sponsors', 'user_id')
    # ### end Alembic commands ###
